steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/flask-app']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: [
  'run', 'deploy', 'flask-app',
  '--image', 'gcr.io/$PROJECT_ID/flask-app',
  '--platform', 'managed',
  '--region', 'us-central1',
  '--allow-unauthenticated',
  '--port', '5000',
  '--set-env-vars', 'GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/serviceAccountKey.json'
]

images:
- 'gcr.io/$PROJECT_ID/flask-app'
